---
title: "Homework 5"
author: 'Morris Greenberg, Presnie Lu, Evan Wyse, Zewen Zhang'
date: "10/17/2019"
output: 
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, message = FALSE,
                      warning = FALSE)
```

```{r}
library(tidyverse)
library(rvest)
library(jsonlite)
library(httr)
```


```{r, cache=TRUE}
test1 <- read_json("http://www2.stat.duke.edu/~sms185/data/fuel/bystore/awaw/awawstore=08078.json")

trycatch1 <- tryCatch(read_json("http://www2.stat.duke.edu/~sms185/data/fuel/bystore/awaw/awawstore=08078.json"),
                      error=function(e){simpleError(e)}, 
                      warning = function(w){simpleWarning(w)})

trycatch2 <- tryCatch(read_json("http://www2.stat.duke.edu/~sms185/data/fuel/bystore/awaw/awawstore=08077.json"),
                      error=function(e){simpleError(e)}, 
                      warning = function(w){simpleWarning(w)})
```

```{r, cache=TRUE}




get_wawa <- function(store_nums){

  store_set <- sprintf("%05d", store_nums)
    
  for(i in store_set){
    #creating link to attempt scraping
    link <- paste0("http://www2.stat.duke.edu/~sms185/data/fuel/bystore/awaw/awawstore=", i, ".json")
  
    #attempts up to 5 times
    for(j in 1:5){
        attempt <- tryCatch(read_json(link),
                            error=function(e){simpleError(e)}, 
                            warning = function(w){simpleWarning(w)})
        #sleeps for a small amount of time
        Sys.sleep(rexp(1))
          
        #if there is not a warning or error message, return
        if(!("message" %in% names(attempt))){
          saveRDS(attempt, file=paste0(paste("dataset", i, sep="_")), ".rds")
          break
        }
    }
    if(as.numeric(store_set) %% 500){
      print(paste("store number", i, sep=": "))
    }
  }
}

get_wawa(c(0:1000, 8000:9000))



```


```{r, }
base_url <- "https://www2.stat.duke.edu/~sms185/data/fuel/bystore/awaw/awawstore="

store_urls<-str_c(base_url,sprintf("%0005d.json",8070:8080))

wawa_data <- map(store_urls,
                 function(store_url) {
                     if (http_error(store_url)==F){
                       return(read_json(store_url))
                     }
                   }
)
```

```{r}
sheetz <- "http://www2.stat.duke.edu/~sms185/data/fuel/bystore/zteehs/regions.html"

#get url 
url_headers <- read_html(sheetz)%>%
  html_nodes(".col-md-2 a") %>%
  html_text() %>%
  trimws()

url <- read_html(sheetz)%>%
  html_nodes(".col-md-2 a") %>%
  html_attr("href")

url <- url[!(url_headers %in% c("", NA, NULL))]


```